### ISSUE TITLE
Passing `shared` into config options results in fail.

### ISSUE THREAD

**Issue by Starwarsfan2099** [x2on/OpenSSL-for-iPhone#145]
Passing `shared` into the config options, my goal is to compile libcryto to a `.dylib`, results in `ld: warning: ./libcrypto.dylib has install name beginning with "/" but it is not from the specified SDK` and `make` fails.

**Comment by oneton** [comment]
The script is not intended for building a shared library. However...

Please provide the full command you use to build. It makes a significant difference whether you use OpenSSL 1.0.2. or 1.1.0 branch.

For 1.0.2 you could try `--noparallel --disable-bitcode`. For 1.1.0 it won't work since no-shared is always added to the options passed to Configure.

**Comment by x2on** [comment]
Closing during inactivity. Please feel free to reopen if you have any new input.
